# Generated by Django 3.0.5 on 2020-04-13 11:38

import django.db.models.deletion
from django.db import migrations, models


def init_stocks(apps, schema_editor):
    Product = apps.get_model("management", "Product")
    Stock = apps.get_model("barman_stocks", "Stock")
    for product in Product.objects.all():
        if not hasattr(product, "stock"):
            Stock.objects.create(product=product)


def reverse_init_stocks(app, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0005_auto_20200412_2240"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_stock",
                    models.BooleanField(default=True, verbose_name="Use stock"),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Stock")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.Product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={"verbose_name": "Stock",},
        ),
        migrations.RunPython(init_stocks, reverse_code=init_stocks),
    ]
